function [setting] = introductionMessage()

    % Introduction Message using typeingTextDisplay() for visual effect
    typingTextDisplay(0.04, "Welcome to the " + ...
        "\n\t\t\t\t");
    
    separationLine(31, "none");

    typingTextDisplay(0.02, "\n\t\t\t\t" + ...
        "-= Automated Grouping System =-" + ...
        "\n\t\t\t\t");

    separationLine(31);

    typingTextDisplay(0.02, "\n" + ...
        "This system is designed to split a crowd into groups based on filter specification from the user." + ...
        "\n" + ...
        "The system is split into 2 settings: " + ...
        "\n\t" + ...
        "1. Simple" + ...
        "\n\t" + ...
        "2. Advance" + ...
        "\n");

    separationLine(97);
    
    % Ask if user want to learn more about settings & store in learnMore
    learnMore = untilCorrectInput('To learn more about the Settings, please type "Yes". Otherise, please type "No": ', "s", ["Yes", "No"]);
    
    % If user want to learn more
    if learnMore == "Yes"

        % Using while-loop, let user explore Settings Descriptions until they want to stop
        while true
            
            % Ask which setting the user want to learn more about
            settingLearnMore = untilCorrectInput("Please choose the setting you want to learn more about (Simple/Advance): ", "s", ["Simple", "Advance"]);

            % If the chosen setting is Simple
            if settingLearnMore == "Simple"
                
                separationLine();
                
                % Display Prompt explaining Simple setting functionality
                typingTextDisplay(0.01, "Simple setting split the crowd into groups based on the following input from the user:" + ...
                    "\n\n\t" + ...
                    "1. Number of Groups" + ...
                    "\n\t" + ...
                    "2. Number of Individuals per Group" + ...
                    "\n\t" + ...
                    "3. Individual’s Name" + ...
                    "\n\n");
                separationLine();
            
            % If the chosen setting is Advance
            else
                separationLine(120);

                % Display Prompt explaining Simple setting functionality
                typingTextDisplay(0.01, "Advance setting allows more flexibility in the splitting of the crowd such as specification on the criteria to split" + ...
                    "\n" + ...
                    "the crowd by (e.g Height, Age, Occupation...), people who should be group together and people who shouldn’t be group together. " + ...
                    "\n" + ...
                    "The setting also allows user to do many groupings (called Events) in one go as well as name those Events and Groups.\n" + ...
                    "The Advance setting will take the following input form the user" + ...
                    "\n\n\t" + ...
                    "1. Toggle Event Feature (Multiple Groupings)" + ...
                    "\n\t\t" + ...
                    "a. Number of Events (Amount of Groupings)" + ...
                    "\n\t\t" + ...
                    "b. Name of Each Event" + ...
                    "\n\t" + ...
                    "2. Toggle Combination/Separation Feature (Combine/Separate Specified Individuals)" + ...
                    "\n\t\t" + ...
                    "a. Choose Between Combine, Separate or Both Options" + ...
                    "\n\t\t" + ...
                    "b. Names of Individual to be Combine or Separate during groupings" + ...
                    "\n\t" + ...
                    "3. Toggle Export As CSV (Download Generated Grouping for each Event as CSV)" + ...
                    "\n\t" + ...
                    "4. Number of Groups for each Event" + ...
                    "\n\t" + ...
                    "5. Number of Individuals per Group for each Event" + ...
                    "\n\t" + ...
                    "6. Individual's Name" + ...
                    "\n\t" + ...
                    "7. Name of Each Group" + ...
                    "\n");

                separationLine(120);

            end
            
            % Ask if the user want to continue exploring settings
            continueLearnMore = untilCorrectInput('Do you want to learning more about the avaliable settings (Yes/No): ', "s", ["Yes", "No"]);
            
            % If user wants to stop
            if continueLearnMore == "No"
                
                % break out of while-loop
                break;
            end
        end
    end
    
    separationLine(97);

    % Ask user to select a setting
    setting = untilCorrectInput("Please Choose Your Setting (Simple/Advance): ", "s", ["Simple", "Advance"]);
    clc;
    fprintf("\n\t\t\t");
    
    % If chosen setting is Simple
    if setting == "Simple"

        % - Display Title & Prompt for Simple setting -
        separationLine(47, "none");
        
        typingTextDisplay(0.02, "\n\t\t\t" + ...
            "===--- Welcome To Simple Grouping System ---===" + ...
            "\n\t\t\t");
        
        separationLine(47);
        fprintf("\n\n");
        
        separationLine(55);
        typingTextDisplay(0.035, "To proceed, please fill in the following customization:" + ...
            "\n\n");

    % If chosen setting is Advance
    else
        % - Display Title & Prompt for Advance setting -
        separationLine(48, "none");
        
        typingTextDisplay(0.02, "\n\t\t\t" + ...
            "===--- Welcome To Advance Grouping System ---===" + ...
            "\n\t\t\t");
        
        separationLine(48);
        fprintf("\n\n");

        separationLine(56);
        typingTextDisplay(0.035, "To proceed, please toggle on/off the following feature:" + ...
            "\n\n")
    end
end