clear; clc;
eventName = "Easter";

% -= Test Case 1 =- (No Com/Sep, No Export CSV, Unique Group Name)
disp(['Input: off off ' ...
    '3 2 ' ...
    'john mike cindy luke rick ken ' ...
    'Friends ' ...
    'Best Friends ' ...
    'Competitions ']);
fprintf(['Expected Output: \n\t' ...
    '- 2 Initial Input Prompt\n\t' ...
    '- essentialGroupInput()\n\t' ...
    '- useExportCSV = Off\n\t' ...
    '- groupTable = Randomized Table with size 2x3 and Group Names ' ...
    '"Friends", "Best Friends" & "Competition" in that order.\n']);
disp("Actual Output:");
[groupTable, useExportCSV] = advance7(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 2 =- (Both, No Export as CSV, Unique Group Name)
disp(['Input: off off ' ...
    '3 2 ' ...
    'john mike cindy luke rick ken ' ...
    'both ' ...
    'john cindy' ...
    'none ' ...
    'luke rick ' ...
    'none ' ...
    'Crush ' ...
    'Friend ' ...
    'Partner']);
fprintf(['Expected Output: \n\t' ...
    '- 2 Initial Input Prompt\n\t' ...
    '- essentialGroupInput()\n\t' ...
    '- Com/Sep Input Instruction\n' ...
    '- Input Prompt To Choose Combine/Separate/Both\n\t' ...
    '- -= Combination List =-\n\t' ...
    '- -= Separation List =-\n\t' ...
    '- useExportCSV = Off\n\t' ...
    '- groupTable = Randomized Table with size 2x3 and Group Names ' ...
    '"Crush", "Friend" & "Partner" in that order.\n']);
disp("Actual Output:");
[groupTable, useExportCSV] = advance7(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 3 =- (No Com/Sep, No Export as CSV, >1 Word Group Name)
disp(['Input: off off ' ...
    '3 2 ' ...
    'john mike cindy luke rick ken ' ...
    'crush & love' ...
    'friend & classmate' ...
    'partner & groupwork']);
fprintf(['Expected Output: \n\t' ...
    '- 2 Initial Input Prompt\n\t' ...
    '- essentialGroupInput()\n\t' ...
    '- Com/Sep Input Instruction\n\t' ...
    '- Input Prompt To Choose Combine/Separate/Both\n\t' ...
    '- -= Combination List =-\n\t' ...
    '- -= Separation List =-\n\t' ...
    '- useExportCSV = Off\n\t' ...
    '- groupTable = Randomized Table with size 2x3 and Group Names '  ...
    '"Crush & Love", "Friend & Classmate" & "Partner & Groupwork" in that order.\n']);
disp("Actual Output:");
[groupTable, useExportCSV] = advance7(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 4 =- (No Com/Sep, No Export as CSV, Repeated Group Name)
disp(['Input: off off ' ...
    '3 2 ' ...
    'john mike cindy luke rick ken ' ...
    'friends ' ...
    'friends ' ...
    'Competitions ']);
fprintf(['Expected Output: \n\t' ...
    '- 2 Initial Input Prompt\n\t' ...
    '- essentialGroupInput()\n\t' ...
    '- Error, VariableNames must be unique\n']);
disp("Actual Output:");
[groupTable, useExportCSV] = advance7(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);


