clear; clc;

eventName = "Easter";

% -= Test Case 1 =- (Correct Input, Combination)
disp('Input: on off ' + ...
    '2 3 ' + ...
    'john mike cindy luke rick ken ' + ...
    'combine ' + ...
    'john mike ' + ...
    'new ' + ...
    'cindy luke rick ' + ...
    'none');
fprintf('Expected Output: \n' + ...
    '- 2 Initial Input Prompt\n' + ...
    '- essentialGroupInput()\n' + ...
    '- Com/Sep Input Instruction\n' + ...
    '- Input Prompt To Choose Combine/Separate/Both\n' + ...
    '- -= Combination List =-\n' + ...
    '- useExportCSV = Off\n' + ...
    '- groupTable = Matrix of zeros with dimension [indPerGroup, groupNum]\n' + ...
    '- combineMatrix: ["John" "Mike" <missing>; "Cindy" "Luke" "Rick"]\n' + ...
    '- Empty separateMatrix\n');
disp("Actual Output:");
[groupTable, useExportCSV] = advance2(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 2 =- (Correct Input, Separation)
disp('Input: on off ' + ...
    '3 2 ' + ...
    'john mike cindy luke rick ken ' + ...
    'separate ' + ...
    'john mike ' + ...
    'new ' + ...
    'cindy luke rick ' + ...
    'none');
fprintf('Expected Output: \n' + ...
    '- 2 Initial Input Prompt\n' + ...
    '- essentialGroupInput()\n' + ...
    '- Com/Sep Input Instruction\n' + ...
    '- Input Prompt To Choose Combine/Separate/Both\n' + ...
    '- -= Separation List =-\n' + ...
    '- useExportCSV = Off\n' + ...
    '- groupTable = Matrix of zeros with dimension [indPerGroup, groupNum]\n' + ...
    '- Empty combineMatrix\n' + ...
    '- separateMatrix: ["John" "Mike" <missing>; "Cindy" "Luke" "Rick"]\n');
disp("Actual Output:");
[groupTable, useExportCSV] = advance2(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 3 =- (Correct Input, Both Same Length Matrixes)
disp('Input: on off ' + ...
    '3 2 ' + ...
    'john mike cindy luke rick ken ' + ...
    'both' + ...
    'john mike ' + ...
    'none ' + ...
    'cindy luke rick ' + ...
    'none');
fprintf('Expected Output: \n' + ...
    '- 2 Initial Input Prompt\n' + ...
    '- essentialGroupInput()\n' + ...
    '- Com/Sep Input Instruction\n' + ...
    '- Input Prompt To Choose Combine/Separate/Both\n' + ...
    '- -= Combination List =-\n' + ...
    '- -= Separation List =-\n' + ...
    '- useExportCSV = Off\n' + ...
    '- groupTable = Matrix of zeros with dimension [indPerGroup, groupNum]\n' + ...
    '- combineMatrix: ["John" "Mike"]\n' + ...
    '- separateMatrix: ["Cindy" "Luke" "Rick"]\n');
disp("Actual Output:");
[groupTable, useExportCSV] = advance2(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);