clear; clc;

eventName = "Easter";

% -= Test Case 1 =- (Combination, No Export as CSV)
disp("Input: on off " + ...
    "3 2 " + ...
    "john mike cindy luke rick ken " + ...
    "combine " + ...
    "john cindy " + ...
    "new " + ...
    "mike ken " + ...
    "none ");
fprintf("Expected Output: \n" + ...
    "- 2 Initial Input Prompt\n" + ...
    "- essentialGroupInput()\n" + ...
    "- Com/Sep Input Instruction\n" + ...
    "- Input Prompt To Choose Combine/Separate/Both\n" + ...
    "- -= Combination List =-\n" + ...
    "- useExportCSV = Off\n" + ...
    "- groupTable: Randomized Table with size 2x3 where John & Cindy are in same group" + ...
    "and Mike & Ken are in same groups which left Luke & Ricky to be in the same group. " + ...
    "Group Name is Group 1 to Group 3.\n");
disp("Actual Output:");
[groupTable, useExportCSV] = advance6(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 2 =- (Separation, No Export as CSV)
disp("Input: on off " + ...
    "3 2 " + ...
    "john mike cindy luke rick ken " + ...
    "separate " + ...
    "john cindy ken" + ...
    "new " + ...
    "luke rick " + ...
    "none ");
fprintf("Expected Output: \n" + ...
    "- 2 Initial Input Prompt\n" + ...
    "- essentialGroupInput()\n" + ...
    "- Com/Sep Input Instruction\n" + ...
    "- Input Prompt To Choose Combine/Separate/Both\n" + ...
    "- -= Separation List =-\n" + ...
    "- useExportCSV = Off\n" + ...
    "- groupTable: Randomized Table with size 2x3 where John, Cindy & Ken are in different " + ...
    "groups and Luke & Rick are in different groups. Group Name is Group 1 to Group 3.\n");
disp("Actual Output:");
[groupTable, useExportCSV] = advance6(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 3 =- (Both, No Export as CSV)
disp("Input: on off " + ...
    "3 2 " + ...
    "john mike cindy luke rick ken " + ...
    "both " + ...
    "john cindy " + ...
    "new " + ...
    "luke mike " + ...
    "none " + ...
    "cindy mike " + ...
    "none ");
fprintf("Expected Output: \n" + ...
    "- 2 Initial Input Prompt\n" + ...
    "- essentialGroupInput()\n" + ...
    "- Com/Sep Input Instruction\n" + ...
    "- Input Prompt To Choose Combine/Separate/Both\n" + ...
    "- -= Combination List =-\n" + ...
    "- -= Separation List =-\n" + ...
    "- useExportCSV = Off\n" + ...
    "- groupTable = Randomized Table with size 2x3 where John & Cindy and " + ...
    "Luke & Mike are in the same group. Cindy & Mike are in different groups, " + ...
    "which leaves Ken & Rick to be in the same group. Group Name is Group 1 to Group 3.\n");
disp("Actual Output:");
[groupTable, useExportCSV] = advance6(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);
