clear; clc;

eventName = "Easter";

% -= Collective Test Case =-
% -> Warning System doesn't stop program until correct input so we'll test
% 2 warning cases and then do 1 case of correct input
% 1. Incorrect String Input - Testing Warning System
% 2. Incorrect Numerical Input (Float, Negative, Lower than 2) - Testing Warning System
% 3. Correct Input, No Combination/Separation & No Export CSV
disp("Input: a off off " + ...
    "2.5 -2 0 1 2 2 " + ...
    "john mike jane luke");
fprintf(['Expected Output: \n' ...
    '1. Warning Message For "a"\n' ...
    '2. Warning Message For "1"\n' ...
    '3. \n' ...
    '- simple() code run which also runs essentialGroupInput() which return a random table\n' ...
    '- useExportCSV return as "Off"' ...
    '- groupTable: Randomized Grouping Table with 3 groups and 2 individuals in each group\n']);
disp("Actual Output:");
[groupTable, useExportCSV] = advance1(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 4 =- (Correct Input, Combination/Separation/Both & No Export CSV)
disp("Input: on off " + ...
    "2 2 " + ...
    "john mike cindy luke " + ...
    "both");
fprintf("Expected Output: \n" + ...
    "2 Initial Input Prompt\n" + ...
    "- essentialGroupInput()\n" + ...
    "- Com/Sep Input Instruction\n" + ...
    "- Input Prompt To Choose Combine/Separate/Both\n" + ...
    "- -= Combination List =- AND/OR -= Separation List =-\n" + ...
    "useExportCSV = Off\n" + ...
    "groupTable = Matrix of zeros with dimension [indPerGroup, groupNum]\n");
disp("Actual Output:");
[groupTable, useExportCSV] = advance1(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 5 =- (Correct Input, No Combination/Separation & Export CSV)
disp("Input: off on " + ...
    "2 2 " + ...
    "john mike cindy luke ");
fprintf("Expected Output: \n" + ...
    "2 Initial Input Prompt\n" + ...
    "- essentialGroupInput()\n" + ...
    "- useExportCSV = On\n" + ...
    "- groupTable: Randomized Grouping Table with 2 groups and 2 individuals in each group\n");
disp("Actual Output:");
[groupTable, useExportCSV] = advance1(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);