clear; clc;
eventName = 'Easter';

% -= Test Case 1 =- (No Com/Sep, No Export as CSV, Repeated Group Name)
disp(['Input: off off '...
    '3 2 '...
    'john mike cindy luke rick ken '...
    'friends '...
    'friends '...
    'New Name '...
    'Competitions ']);
fprintf(['Expected Output: \n'...
    '- 2 Initial Input Prompt\n'...
    '- essentialGroupInput()\n'...
    '- useExportCSV = Off\n'...
    '- groupTable = Randomized Table with size 2x3. Group Names are '...
    '"Friends", "New Name" & "Competitions" in that order.\n']);
disp("Actual Output:");
[groupTable, useExportCSV] = advance(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 2 =- (Both, No Export as CSV, Repeated Group Name)
disp(['Input: on off '...
    '3 2 '...
    'john mike cindy luke rick ken '...
    'both '...
    'john cindy'...
    'none '...
    'luke rick '...
    'none '...
    'Crush '...
    'Friend '...
    'Friend '...
    'New Name']);
fprintf(['Expected Output: \n'...
    '- 2 Initial Input Prompt\n'...
    '- essentialGroupInput()\n'...
    '- Com/Sep Input Instruction\n'...
    '- Input Prompt To Choose Combine/Separate/Both\n'...
    '- -= Combination List =-\n'...
    '- -= Separation List =-\n'...
    '- useExportCSV = Off\n'...
    '- groupTable = Randomized Table with size 2x3. Group Names are '...
    '"Crush", "Friend" & "New Name" in that order.\n']);
disp("Actual Output:");
[groupTable, useExportCSV] = advance(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);

pauser = input("Press Enter To Continue");
clc;

% -= Test Case 3 =- (Both, No Export as CSV, Invalid Number of Input for Combination & Separation Matrix)
disp(['Input: on off '...
    '3 3 '...
    'john mike cindy luke rick ken hans jack bach'...
    'both '...
    'new '...
    'john '...
    'new '...
    'none ' ...
    'john ' ...
    'none ' ...
    'john cindy ' ...
    'none ' ...
    'new '...
    'luke '...
    'new '...
    'none ' ...
    'luke ' ...
    'none ' ...
    'luke ken ' ...
    'none ' ...
    'Crush '...
    'Friend '...
    'Partner ']);
fprintf(['Expected Output: \n'...
    '- 2 Initial Input Prompt\n'...
    '- essentialGroupInput()\n'...
    '- Com/Sep Input Instruction\n'...
    '- Input Prompt To Choose Combine/Separate/Both\n'...
    '- -= Combination List =-\n' ...
    '- Warning Message Saying Insufficient Input'...
    '- Warning Message Saying Insufficient Input'...
    '- Warning Message Saying Insufficient Input'...
    '- Warning Message Saying Insufficient Input'...
    '- -= Separation List =-\n'...
    '- Warning Message Saying Insufficient Input'...
    '- Warning Message Saying Insufficient Input'...
    '- Warning Message Saying Insufficient Input'...
    '- Warning Message Saying Insufficient Input'...
    '- useExportCSV = Off\n'...
    '- groupTable = Randomized Table with size 3x3. Group Names are '...
    '"Crush", "Friend" & "Partner" in that order.\n']);
disp("Actual Output:");
[groupTable, useExportCSV] = advance(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);