clear; clc;

eventName = "Easter";

% -= Test Functionality =- (Both, Separating Individuals Inputted To Be Combine)
disp('Input: on off ' + ...
    '3 2 ' + ...
    'john mike cindy luke rick ken ' + ...
    'both ' + ...
    'john cindy ' + ...
    'none ' + ...
    'john mike cindy ' + ...
    'none ');
fprintf('Expected Output: \n' + ...
    '- 2 Initial Input Prompt\n' + ...
    '- essentialGroupInput()\n' + ...
    '- Com/Sep Input Instruction\n' + ...
    '- Input Prompt To Choose Combine/Separate/Both\n' + ...
    '- -= Combination List =-\n' + ...
    '- -= Separation List =-\n' + ...
    '- Cannot separate John and Cindy because they are inputted to be combine warning message\n' + ...
    '- useExportCSV = Off\n' + ...
    '- groupTable = Matrix of zeros with dimension [indPerGroup, groupNum]\n' + ...
    '- combineMatrix: ["John" "Cindy"]\n' + ...
    '- separateMatrix: ["John" "Mike"]\n');
disp("Actual Output:");
[groupTable, useExportCSV] = advance5(eventName);
fprintf("useExportCSV: %s\n", useExportCSV);
disp(groupTable);