clear; clc;

% Variables
eventName = "Table";
matrix = zeros(5, 5);
groupName = ["Group 1" "Group 2" "Group 3" "Group 4" "Group 5"];
tableToExport = array2table(matrix, "VariableNames", groupName);

% -= Test Export Functionality =-
fprintf(['Input: \n\t' ...
    '- Event Name: Table\n\t' ...
    '- Table: Table with VariableNames "Group 1" to "Group 5" & 5x5 data of 0\n']);
fprintf(['Expected Output: n\\t' ...
    '- Message Box saying the event grouping has been successfully exported\n\t' ...
    '- A downloaded csv file in the folder where groupAlgorithm is located\n\t' ...
    '- File name: "Table.csv"\n\t' ...
    '- Top row of each columns with each elements of groupName\n\t' ...
    '- Body: 5x5 data of 0\n']);
disp("Actual Output: ");
exportAsCSV(eventName, tableToExport);