clear; clc;

% -= Test Functionality =- (Valid Input)
fprintf(['Input: \n\t' ...
    '- 1st Time: "yes" "simple" "yes" "advance" "no" "simple"\n\t' ...
    '- 2nd Time: "no" "advance"\n\n']);
fprintf("Expected Output: \n\t" + ...
    "- 1st Time:\n\t\t" + ...
    "- All text correctly displayed with typing effect\n\t\t" + ...
    "- All Input propmt displayed correctly\n\t\t" + ...
    "- No warning message pop-up\n\t\t" + ...
    "- Simple description displayed when user input Simple when learnMore is Yes & the same for Advance\n\t\t" + ...
    "- The input prompt to choose the setting is correctly displayed when learnMore is No\n\t\t" + ...
    "- Command Window is clear before displaying Simple title & prompt\n\t\t" + ...
    "- Variable setting1 is returned as Simple\n\t" + ...
    "- 2nd Time:\n\t\t" + ...
    "- All text correctly displayed with typing effect\n\t\t" + ...
    "- All Input propmt displayed correctly\n\t\t" + ...
    "- No warning message pop-up\n\t\t" + ...
    "- The input prompt to choose the setting is correctly displayed when learnMore is No\n\t\t" + ...
    "- Command Window is clear before displaying Advance title & prompt\n\t\t" + ...
    "- Variable setting2 is returned as Advance\n");
disp("Actual Output:");
setting1 = introductionMessage();

fprintf("\n\n\n");

setting2 = introductionMessage();
fprintf("- setting1: %s\n" + ...
    "- setting2: %s\n\n", setting1, setting2);

pauser = input("Press Enter To Continue");
clc;

% -= Test Functionality =- (Invalid Input)
fprintf('Input: "yup" "yes" "1" "simple" "yeah" "yes" "2" "advance" "nope" "no" "simpla" "simple"\n');
fprintf("Expected Output: \n\t" + ...
    "- All text correctly displayed with typing effect\n\t" + ...
    "- All Input propmt displayed correctly\n\t" + ...
    "- Warning message pop-up saying input should be Yes or No\n\t" + ...
    "- Warning message pop-up saying input should be Simple or Advance\n\t" + ...
    "- Simple description displayed when user input Simple when learnMore is Yes & the same for Advance\n\t" + ...
    "- Warning message pop-up saying input should be Simple or Advance\n\t" + ...
    "- Warning message pop-up saying input should be Yes or No\n\t" + ...
    "- The input prompt to choose the setting is correctly displayed when learnMore is No\n\t" + ...
    "- Warning message pop-up saying input should be Simple or Advance\n\t" + ...
    "- Command Window is clear before displaying Simple title & prompt\n\t" + ...
    "- Variable setting is returned as Simple\n\t");
disp("Actual Output:");
setting = introductionMessage();
fprintf("- setting: %s\n", setting);