clear; clc;

% -= Test Case 1 =- (Side Spacing)
text = "   This is a normal text with side spaces   ";
fprintf("Input: %s\n", text);
fprintf(['Expected Output: \n\t' ...
    '- returnText: "This Is A Normal Text With Side Spaces"\n\t' ...
    '- class(returnText): string\n']);
returnText = title(text);
fprintf(['Actual Output: \n\t' ...
    '- returnText: "%s"\n\t' ...
    '- class(returnText): %s\n\n'], returnText, class(returnText));

% -= Test Case 2 =- (lowercase input)
text = "this is a text with all lower case";
fprintf("Input: %s\n", text);
fprintf(['Expected Output: \n\t' ...
    '- returnText: "This Is A Text With All Lower Case"\n\t' ...
    '- class(returnText): string\n']);
returnText = title(text);
fprintf(['Actual Output: \n\t' ...
    '- returnText: "%s"\n\t' ...
    '- class(returnText): %s\n\n'], returnText, class(returnText));

% -= Test Case 3 =- (UPPERCASE input)
text = "THIS IS A TEXT WITH ALL UPPER CASE";
fprintf("Input: %s\n", text);
fprintf(['Expected Output: \n\t' ...
    '- returnText: "This Is A Text With All Upper Case"\n\t' ...
    '- class(returnText): string\n']);
returnText = title(text);
fprintf(['Actual Output: \n\t' ...
    '- returnText: "%s"\n\t' ...
    '- class(returnText): %s\n\n'], returnText, class(returnText));

% -= Test Case 4 =- (Mixed CASE input)
text = "ThIS iS a TeXt wiTH mixED CaSE";
fprintf("Input: %s\n", text);
fprintf(['Expected Output: \n\t' ...
    '- returnText: "This Is A Text With Mixed Case"\n\t' ...
    '- class(returnText): string\n']);
returnText = title(text);
fprintf(['Actual Output: \n\t' ...
    '- returnText: "%s"\n\t' ...
    '- class(returnText): %s\n'], returnText, class(returnText));